### ISSUE TITLE
UIButton :highlight state style delay

### ISSUE THREAD

**Issue by wprater** [Pixate/pixate-freestyle-ios#106]
I have a style to darken the color of a button on tap (:highlight), but on the device, the style seems to be delayed.  

Is this normal?

**Comment by jshier** [comment]
For anyone who winds up on this issue after Googling delayed pressed state, turns out you can fix the issue mentioned here, for which the Apple dev forums link no longer works, by updating the storyboard to use safe areas (ooold project) the button can go into the highlighted state immediately.
