### ISSUE TITLE
Is under active development?

### ISSUE THREAD

**Issue by SandroMachado** [Pixate/pixate-freestyle-ios#177]
Is pixate-freestyle-ios for iOS under active development? Does it support swift?

**Comment by cliftonlabrum** [comment]
The last commit was 9 months ago. The last release was in June of 2014. I'll let you draw your own conclusions. :)

**Comment by SandroMachado** [comment]
Yup, looks like it isn't under active development!

**Comment by VincentChann** [comment]
Same question here.

Does "pixate-freestyle-ios" still under active development?
Last commit was 11 months ago.

Thank you.

**Comment by SandroMachado** [comment]
It is not, so I closed the issue.
