### ISSUE TITLE
Docs down

### ISSUE THREAD

**Issue by buelsenfrucht** [Pixate/pixate-freestyle-ios#180]
Hi guys,

don't know whether this is worth an issue, but the docs for iOS are down since yesterday, always getting 404 error...

**Comment by bjaskj** [comment]
I have also pinged them on twitter about this without any success. It was a shame since I just discovered this. I ended up building the docs locally.

**Comment by andrewholt** [comment]
Hey guys, we're looking into this now, thanks for the heads up.

**Comment by andrewholt** [comment]
The docs are up again!

**Comment by uzegonemad** [comment]
Back down again...
