### ISSUE TITLE
Link to documentation is not valid anymore

### ISSUE THREAD

**Issue by nikita-leonov** [Pixate/pixate-freestyle-ios#183]
Link http://pixate.github.io/pixate-freestyle-ios/ is not working anymore. Any plans to re-publish it somewhere?

**Comment by Pitsko** [comment]
+

**Comment by uzegonemad** [comment]
Well, the likelihood of hearing back from the developers seems slim.

Here's a mirror of the docs: https://uzegonemad.github.io/pixate-freestyle-ios/

**Comment by Dune2015** [comment]
Please bring back the object documentation. Without it, I have to depend on sample code to figure out what attribute is working. Thanks.

**Comment by andrewholt** [comment]
We restored the docs, but it looks like the Developer Reference is still down. We're working on this now.

**Comment by andrewholt** [comment]
OK, the dev documentation has been restored: http://pixate.github.io/pixate-freestyle-ios//dev-reference.html. 

Let us know if you see any more issues there.

**Comment by Dune2015** [comment]
Thanks Andrew.
